name: Worlds
main: net.preoccupied.bukkit.worlds.WorldsPlugin
version: 0.1
author: obriencj@gmail.com
database: false
description: Load multiple worlds
order: postworld


commands:
  world:
    desciption: "Teleport to a world's default spawn point"
    usage: /world WORLD-NAME
    permission: preoccupied.worlds.teleport

  world-list:
    description: A list of available worlds
    usage: /world-list
    permission: preoccupied.worlds.info

  world-info:
    description: Information on a specific world
    usage: /world-info WORLD-NAME
    permission: preoccupied.worlds.info

  world-enable:
    description: Enables a world
    usage: /world-enable WORLD-NAME
    permission: preoccupied.worlds.admin

  world-disable:
    description: Disables a world
    usage: /world-disable WORLD-NAME
    permission: preoccupied.worlds.admin


permissions:
  preoccupied.worlds.admin:
    description: Administrative options for multi-world support
    default: op
    children:
      preoccupied.worlds.info: true
      preoccupied.worlds.teleport: true

  preoccupied.worlds.advanced:
    description: Advanced users options for multi-world support
    default: false
    children:
      preoccupied.worlds.info: true
      preoccupied.worlds.teleport: true
      
  preoccupied.worlds.info:
    description: Listing and getting information for worlds
    default: false

  preoccupied.worlds.teleport:
    description: Teleport to the spawn location of a world
    default: false


# The end.
